### ISSUE TITLE
Add cucumberOpts to Maven mojo

### ISSUE THREAD

**Issue by mariushaugen** [cucumber-attic/cuke4duke#1]
<pre><code>
/**
 * @parameter expression="${cucumber.cucumberOpts}"
 */
private String[] cucumberOpts;
</code></pre>

....

<pre><code>

if(cucumberOpts != null) {
            for (String opt : cucumberOpts) {
                allArgs.add(opt);
            }
        }

</code></pre>

....

<pre><code>
&lt;configuration&gt;
  &lt;jrubyHome&gt;...&lt;/jrubyHome&gt;
  &lt;cucumberOpts&gt;
    &lt;cucumberOpt&gt;--language&lt;/cucumberOpt&gt;
    &lt;cucumberOpt&gt;no&lt;/cucumberOpt&gt;
    &lt;/cucumberOpts&gt;
&lt;/configuration&gt;

</code></pre>

**Comment by oc** [comment]
Added cucumber.args to my master...

**Comment by aslakhellesoy** [comment]
Trying to close an issue from Git. Closed by 1708b2ab00d27a316295e84f9f68088662ba82b6.
