### ISSUE TITLE
can't use multiline strings

### ISSUE THREAD

**Issue by darrinholst** [cucumber-attic/cuke4duke#10]
I tried using a multiline string and got the follwing...

java.lang.IllegalArgumentException: Sorry, cuke4duke doesn't know how to convert a line 1
[INFO]       line 2     (class org.jruby.RubyObject) to type class java.lang.String (NativeException)
[INFO]       cuke4duke/internal/StringConverter.java:43:in `convertObject'

I have a fix at http://github.com/darrinholst/cuke4duke/commit/1004d466c34b02d6d2b5f0036478736a7907bb0d which does a String.valueOf instead of just casting to a String. Not sure if this is the right way, but it worked for me.

**Comment by aslakhellesoy** [comment]
Fixed in 0.1.2
