### ISSUE TITLE
Cuke4Duke Spring integration - maven build hangs

### ISSUE THREAD

**Issue by woodenboat** [cucumber-attic/cuke4duke#101]
I'm using the Cuke4Duke Spring integration to inject some spring managed beans into my cucumber step classes. Running a "maven clean integration-test" from either the command line or via my jenkins ci server, although all the tests pass the maven build hangs and will not exit.
I'm using the same injection of beans into my unit tests and running "maven clean package" all the tests pass and the maven build exits cleanly. Has anyone come across the same issues?

Stephen

**Comment by darrinholst** [comment]
Yeah, I actually have come across this issue also. I wasn't in a position to track it down at the time so I just reverted to an older version. I'll try to reproduce it and track it down.

**Comment by woodenboat** [comment]
When you say older version you mean an older version of cuke4duke or an older version of maven? When I get a hanging build and connect jconsole I can see several threads waiting around, but as these are all spring managed beans I'd expect them to be cleaned up after the test finishes.
Thanks for following this up.

Stephen

**Comment by darrinholst** [comment]
Older version of cuke4duke, I'm currently using 0.3.2, when switching to 0.4.3 it hangs.

**Comment by darrinholst** [comment]
Seems to be caused by this change to cucumber...

https://github.com/aslakhellesoy/cucumber/commit/e5f49afd47591dd2789abcae91a47cca91c1ba6f#L2L6

**Comment by darrinholst** [comment]
Well, I tried, but got into something way over my head :)

I tracked down where it's using the Java class from ant to kick off the process and then it does a process.waitFor() where it then sits there forever.

Did a little googling and this might be related, but I'm not sure - http://jira.codehaus.org/browse/JRUBY-3780
