### ISSUE TITLE
Cannot find cuke4duke-0.4.2.jar

### ISSUE THREAD

**Issue by kirafaye** [cucumber-attic/cuke4duke#102]
Hi
Im trying to install cuke4duke using maven. I downloaded v0.4.2. changed directories to point to example/java-webdriver and ran
mvn -Dcucumber.installGems=true  cuke4duke:cucumber
However I get an error back saying:
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke: Java WebDriver Example 0.4.2
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.elasticpath.com/archiva/repository/custom/cuke4duke/cu
ke4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://maven.elasticpath.net/archiva/repository/snapshots/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://maven.elasticpath.net/archiva/repository/extras/cuke4duke/cu
ke4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://maven-ps.elasticpath.net/archiva/repository/extras/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://maven.elasticpath.com/archiva/repository/snapshots/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://nexus.openqa.org/content/repositories/releases/cuke4duke/cuk
e4duke/0.4.2/cuke4duke-0.4.2.pom
Downloading: http://repository.codehaus.org/cuke4duke/cuke4duke/0.4.2/cuke4duke-
0.4.2.pom
Downloading: http://cukes.info/maven/cuke4duke/cuke4duke/0.4.2/cuke4duke-0.4.2.p
om
Downloading: http://maven.elasticpath.net/archiva/repository/internal/cuke4duke/
cuke4duke/0.4.2/cuke4duke-0.4.2.pom
[WARNING] The POM for cuke4duke:cuke4duke:jar:0.4.2 is missing, no dependency in
formation available
Downloading: http://maven.elasticpath.com/archiva/repository/custom/cuke4duke/cu
ke4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://maven.elasticpath.net/archiva/repository/snapshots/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://maven.elasticpath.net/archiva/repository/extras/cuke4duke/cu
ke4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://maven-ps.elasticpath.net/archiva/repository/extras/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://maven.elasticpath.com/archiva/repository/snapshots/cuke4duke
/cuke4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://nexus.openqa.org/content/repositories/releases/cuke4duke/cuk
e4duke/0.4.2/cuke4duke-0.4.2.jar
Downloading: http://repository.codehaus.org/cuke4duke/cuke4duke/0.4.2/cuke4duke-
0.4.2.jar
Downloading: http://cukes.info/maven/cuke4duke/cuke4duke/0.4.2/cuke4duke-0.4.2.j
ar
Downloading: http://maven.elasticpath.net/archiva/repository/internal/cuke4duke/
cuke4duke/0.4.2/cuke4duke-0.4.2.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.629s
[INFO] Finished at: Mon Mar 21 11:26:30 PDT 2011
[INFO] Final Memory: 3M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cuke4duke-java-webdriver-example: Coul
d not resolve dependencies for project cuke4duke:cuke4duke-java-webdriver-exampl
e:jar:0.4.2: Could not find artifact cuke4duke:cuke4duke:jar:0.4.2 in custom (ht
tp://maven.elasticpath.com/archiva/repository/custom) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

Ive looked for cuke4duke-0.4.2.jar on the internet to place it manually in my .m2 but couldnt find it anywhere. Any ideas?
K

**Comment by aslakhellesoy** [comment]
On Mar 21, 2011, at 18:35, kirafaye
reply@reply.github.com
wrote:

> Hi
> Im trying to install cuke4duke using maven. I downloaded v0.4.2.

Try 0.4.3. Older versions got lost in a server transition I'm afraid.

http://cukes.info/maven/cuke4duke/cuke4duke/

Aslak

**Comment by kirafaye** [comment]
Okay I downloaded 0.4.3 and fixed the versions in my pom.xml. It seems to successfully install cuke4duke but is still getting a JRuby failure. This is my output.

C:\Program Files (x86)\aslakhellesoy-cuke4duke-4_2\examples\java-webdriver>mvn -
Dcucumber.installGems=true cuke4duke:cucumber
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
cuke4duke:cuke4duke-java-webdriver-example:jar:0.4.3
[WARNING] 'build.plugins.plugin.version' for cuke4duke:cuke4duke-maven-plugin is
 missing. @ line 70, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-sour
ce-plugin is missing. @ cuke4duke:parent:0.4.3, C:\Program Files (x86)\aslakhell
esoy-cuke4duke-4_2\pom.xml, line 253, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke: Java WebDriver Example 0.4.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- cuke4duke-maven-plugin:0.4.3:cucumber (default-cli) @ cuke4duke-java-
webdriver-example ---
[INFO] JRuby limited openssl loaded. http://jruby.org/openssl
[INFO] gem install jruby-openssl for full support.
[INFO] Successfully installed cuke4duke-0.4.3
[INFO] 1 gem installed
[INFO] WARNING: Couldn't detect your output codepage. Assuming it is 1252. You m
ay have to chcp 1252 or SET CUCUMBER_OUTPUT_ENCODING=cp1252.
[INFO] Code:
[INFO]
[INFO] No such file or directory - Files (Errno::ENOENT)
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
feature_file.rb:55:in `initialize'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
feature_file.rb:55:in`open'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
feature_file.rb:55:in `source'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
feature_file.rb:37:in`parse'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime/features_loader.rb:28:in `load'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime/features_loader.rb:26:in`each'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime/features_loader.rb:26:in `load'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime/features_loader.rb:14:in`features'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime.rb:132:in `features'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
runtime.rb:45:in`run!'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
cli/main.rb:43:in `execute!'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/
cli/main.rb:20:in`execute'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/bin/cucumber:
14
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cucumber-0.10.2/bin/cucumber:
4:in `load'
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cuke4duke-0.4.3/bin/cuke4duke
:4
[INFO] C:/Users/kmccoan/.m2/repository/.jruby/gems/cuke4duke-0.4.3/bin/cuke4duke
:19:in`load'
[INFO] C:\Users\kmccoaFeatures:
[INFO] n.m2\repository.jruby\bin\cuke4duke:19
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.351s
[INFO] Finished at: Mon Mar 21 13:10:43 PDT 2011
[INFO] Final Memory: 3M/76M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cuke4duke:cuke4duke-maven-plugin:0.4.3:cucumber (
default-cli) on project cuke4duke-java-webdriver-example: JRuby failed. Java ret
urned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

Any clue as to why JRuby would be failing?

**Comment by darrinholst** [comment]
Just a guess, but try running it from a directory without spaces in the path.

**Comment by kirafaye** [comment]
Thank you so much. Works like a charm
