### ISSUE TITLE
cuke4duke wiki has dead links

### ISSUE THREAD

**Issue by elnopintan** [cucumber-attic/cuke4duke#108]

**Comment by mylene** [comment]
Workaround: replace /aslakhellesoy/ with /cucumber/ in the browser address bar

**Comment by elnopintan** [comment]
Thank you. But they should fix this bug in order navigate the wiki properly

**Comment by aslakhellesoy** [comment]
@elnopintan: "they" is the community of users and developers, which includes you. All links should be fixed now. If you find more broken links, fell free to correct them yourself.

**Comment by elnopintan** [comment]
Sorry, if it sounded rude. I didn't have time to fix it myself. My intent was to provide advice about the issue.

**Comment by aslakhellesoy** [comment]
no offense taken :-) thanks for pointing it out. FWIW the links were broken due to this move: http://groups.google.com/group/cukes/browse_thread/thread/5e63a6f3e69d2ce0
