### ISSUE TITLE
Enable steps to be pending

### ISSUE THREAD

**Issue by torbjornvatn** [cucumber-attic/cuke4duke#13]
We need a pending method or annotation that makes the cuke4duke steps yellow when they are pending.

**Comment by aslakhellesoy** [comment]
@Pending sounds nice. WDYT?

**Comment by torbjornvatn** [comment]
I'll give it a try.

**Comment by aslakhellesoy** [comment]
I have done it already. Will push when I get home. Had to do some static funkiness with JRuby runtime to be able to raise the Cucumber::Pending exception from Java.

**Comment by aslakhellesoy** [comment]
Added new @Pending annotation that can be used as a substitute for Ruby-Cucumber's #pending method. Closed by 1eb7936c19790c191e5087883f94ef77dd01f6f2
