### ISSUE TITLE
better grails example

### ISSUE THREAD

**Issue by rsilva4-zz** [cucumber-attic/cuke4duke#130]
Thu current example for grails is just a empty grails app.

**Comment by aslakhellesoy** [comment]
Yep. And Cuke4Duke is a dead project.

See https://github.com/cucumber/cucumber-jvm

**Comment by rsilva4-zz** [comment]
Thanks man for your quick reply! I'm already trying to use grails, geb and cucumber-jvm. Just a quick question hot to read DataTables un groovy steps? I have been looking into the examples but was unable to figured it out. Thanks again!

**Comment by aslakhellesoy** [comment]
Hi. Please ask on the cucumber mailing list
