### ISSUE TITLE
The @Before annotation of a superclass has no effect in a subclass

### ISSUE THREAD

**Issue by torbjornvatn** [cucumber-attic/cuke4duke#15]
If a steps class subclasses another steps class the @Before annotated setUp method of the superclass is not invoked when a step method in the subclass is called.

**Comment by aslakhellesoy** [comment]
Bugfix: The @Before annotation of a superclass has no effect in a subclass. (Works now if superclass is abstract). Closed by c79c20e2d61fb626a786abe25ae15ec63d9bba44
