### ISSUE TITLE
Maven should only print java command on failures if -e switch is passed to mvn.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#16]
In CucumberMojo - only add cmd(jruby) to the exception's message if mvn was run with -e. Need to find out how to inspect that.

**Comment by darrinholst** [comment]
-e is currently just used to show stack traces. I took a quick look through the maven source and didn't find that it was making cli options available to plugins anywhere (it could be hiding in there somewhere though, who knows)

If you use -X there are a few places where it prints the java command, I'd vote for just taking it out of the exception message completely.

**Comment by aslakhellesoy** [comment]
I added the command for debugging reasons. Things were failing, and I didn't figure out why until I added this. Admittedly, this was in order to diagnose cuke4duke/cucumber insternals. It's still useful, but I agree it should be off by default.

Can you elaborate on why you don't think it's a good idea to enable this with -X ?

**Comment by darrinholst** [comment]
sure, when you add the -X parameter you get the java command that was ran a couple times. Here is the output from the simple example http://gist.github.com/180268, line 424 has it and line 444 also has it.

**Comment by aslakhellesoy** [comment]
No longer print java command on failures. If needed it can be printed by passing -X to Maven. Closed by 7eafe2f3761350d5f02d6a94669dcc64e763f8ee

**Comment by matthewmccullough** [comment]
I'm slow to reply Darrin -- but in looking at Maven 2.2 code, the CLI is saved into a CommandLine struct which is then liberally passed around.  Specifically line 511 passes it into the "kickstart" of the main maven execution.  Would have to follow it further to see if this is put into Plexus DI as a singleton, or available via a IOC call from a plugin.  Hope that helps a little...

http://svn.apache.org/viewvc/maven/maven-2/branches/maven-2.2.x/maven-core/src/main/java/org/apache/maven/cli/MavenCli.java?view=markup
