### ISSUE TITLE
system properties passed to maven aren't available in the steps

### ISSUE THREAD

**Issue by darrinholst** [cucumber-attic/cuke4duke#17]
When I pass system properties into maven via the -D parameter they should be available in my steps. Since the jvm is forked they aren't propagated. The java ant task that is used to run java makes it simple to fix this. Fix is at http://github.com/darrinholst/cuke4duke/commit/65d5115491c2fb54fe524151238f6aaa23680835

**Comment by aslakhellesoy** [comment]
Your change seems to break cuke4duke. Please try running everything as described on the Contributing page. You'll see that no examples are run. It seems like your change resets user.dir (and possibly all other system properties).

**Comment by darrinholst** [comment]
Oops, sorry, didn't see the profile selection to run the examples.

Yeah, it appears setting the user.dir overwrites setting the working directory and looking at the command it generates seems a hackish way to do that. Who knows what else that affects.

I also didn't see the jvmArgs on the plugin configuration which is exactly what I need. Closing this ticket.

**Comment by aslakhellesoy** [comment]
Thanks Darrin. Closing it then.
