### ISSUE TITLE
Implement hooks in cucumber_java

### ISSUE THREAD

**Issue by goodneema** [cucumber-attic/cuke4duke#2]
For Java developers, it would be much easier if cucumber_java provides hooks functionality , so that we can use hooks feature in java applications

Thanks,
Neema.

**Comment by aslakhellesoy** [comment]
Ok. It will probably look something like this:

<pre>
public class Whatever {
    @Before
    public void before() {
        // stuff
    }
}

</pre>

**Comment by aslakhellesoy** [comment]
This is implemented on master. Currently you have to pass an empty String to @Before - @Before(""). The idea is to be able to pass tags, just like with pure Ruby cucumber.

**Comment by olemartin** [comment]
It seems like the tag functionality is not working in 0.1.8. I have the following code
    @Before("@mytag")
    public void....

this method is ran before all my scenarios, even when they don't have any tags.

**Comment by aslakhellesoy** [comment]
Could you please open a new ticket for this instead of commenting on an old one that was marked as closed?

**Comment by olemartin** [comment]
Yes, of coutse. I didn't notice that it was closed
