### ISSUE TITLE
Cuke4Duke breaks plain Spring JUnit-Tests (non-cucumber)

### ISSUE THREAD

**Issue by fabianbuch** [cucumber-attic/cuke4duke#23]
Adding cuke4duke mvn dependency leads to failing junit tests which have the annotation @Autowired. This behaviour is demonstrated in my fork (http://github.com/fabianbuch/cuke4duke) in the testclass PlainUnitTest. The field annotated with @Autowired stays null.

**Comment by aslakhellesoy** [comment]
Why are you expecting this to happen? Is this something that happens automatically in non-cucumber Spring projects that use @Autowire on JUnit tests?

**Comment by fabianbuch** [comment]
My fault. I'm new to Spring and Cuke4Duke. Spring 3.0.0M4 requires exactly JUnit 4.6 and I used JUnit 4.7. Going back to 4.6 and my app works, so this ticket can be closed as invalid.

**Comment by aslakhellesoy** [comment]
Closed
