### ISSUE TITLE
Problems adding custom formatters to features/support

### ISSUE THREAD

**Issue by torbjornvatn** [cucumber-attic/cuke4duke#24]
I'm trying to add a custom formatter to my cuke4duke project following the instructions found here: http://wiki.github.com/aslakhellesoy/cucumber/custom-formatters

I'm adding a --format WikiFormatter argument and it when run it returns:
    [WARNING] no such file to load -- wiki_formatter
    [WARNING] Error creating formatter: WikiFormatter (LoadError)
    [WARNING] file:/home/torbjorn/.m2/repository/org/jruby/jruby-complete/1.3.1/jruby-complete-1.3.1.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    [WARNING] file:/home/torbjorn/.m2/repository/org/jruby/jruby-complete/1.3.1/jruby-complete-1.3.1.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/constantize.rb:14:in`constantize'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/configuration.rb:94:in `formatter_class'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/configuration.rb:77:in`build_formatter_broadcaster'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/configuration.rb:63:in `map'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/configuration.rb:63:in`build_formatter_broadcaster'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/main.rb:51:in `execute!'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/../lib/cucumber/cli/main.rb:23:in`execute'
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/cucumber:9
    [WARNING] /home/torbjorn/.m2/repository/.gem/gems/cucumber-0.3.101/bin/cucumber:19:in `load'
    [WARNING] /home/torbjorn/.m2/repository/.gem/bin/cucumber:19

Seems like the files in features/support is not load into the classpath somehow.

**Comment by torbjornvatn** [comment]
Asked the question on the google group instead

**Comment by aslakhellesoy** [comment]
You need to --require the directory (or file) where your formatter lives. The wiki page has been updated.
