### ISSUE TITLE
Exceptions raised by assert in Clojure don't properly bubble up

### ISSUE THREAD

**Issue by bmabey** [cucumber-attic/cuke4duke#27]
In a clojure feature if you have an assert call that fails and raises an exception you do not see the proper exception in the output.  You should see something like:

java.lang.Exception: Assert failed: (= 5 10)

But instead you see a:

java.lang.reflect.InvocationTargetException: null (NativeException)

Here is a full backtrace:
http://pastie.org/628565

**Comment by aslakhellesoy** [comment]
This is solved on my master
