### ISSUE TITLE
Error when running mvn clean install on latest cuke4duke

### ISSUE THREAD

**Issue by torbjornvatn** [cucumber-attic/cuke4duke#30]
I get a the following error when running <code>mvn clean install</code> on the latest cuke4duke from GitHub:

_[WARNING] undefined method `available_step_definition' for #Cucumber::ClassSupport::ClassLanguage:0xea04d4 (NoMethodError)_

Full stacktrace here: http://gist.github.com/199223

**Comment by aslakhellesoy** [comment]
You have to run against my cucumber master
