### ISSUE TITLE
missing dep on ioke.lang:ikj:jar:0.4.0-1

### ISSUE THREAD

**Issue by ssmithstone** [cucumber-attic/cuke4duke#32]
running mvn cuke4duke:cucumber maven is unable to resolve the dependency

**Comment by aslakhellesoy** [comment]
Are you building with -o ?
They are there: http://github.com/aslakhellesoy/cuke4duke/tree/master/examples/ioke/maven/ioke/lang/ikj/

**Comment by aslakhellesoy** [comment]
What OS are you on? Is this Windows being finnicky again?

**Comment by ssmithstone** [comment]
i am not building with -o and i running os x 10.5.x
the log is here http://www.pastie.org/657427
the work around i managed to do was to clone the ikj and install it locally

**Comment by aslakhellesoy** [comment]
Looks like the local URL is not expanded:

file://${project.basedir}/../examples/ioke/maven

On my machine this expands, and maven successfully finds the jar. Any idea why maven won't expand it? Im on mvn 2.2.1.

If you're on a lower maven version, could you try to upgrade?

Ola has said he'll push Ioke jars to http://repository.codehaus.org/ but it seems to be delayed because of a slow process to get the right credentials...

**Comment by ssmithstone** [comment]
mvn -version
Apache Maven 2.2.1 (r801777; 2009-08-06 20:16:01+0100)
Java version: 1.5.0_20
Java home: /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x" version: "10.5.8" arch: "i386" Family: "unix"

**Comment by aslakhellesoy** [comment]
I think I misunderstood. You're building _your own_ project and not trying to build the cuke4duke project?

If that's the case, maybe marking the ioke jars as provided would help?

**Comment by ssmithstone** [comment]
ah sorry, my fault yes im running my own project using cuke4duke / java and spring , and it fails also in the example it fails,
however are the iok files necessary for me to run against a spring app, maybe marking them as optional in the pom

**Comment by aslakhellesoy** [comment]
Could you try 0.1.8-SNAPSHOT instead? I just deployed it, using optional like you suggested.

**Comment by ssmithstone** [comment]
that seems to work now, i removed the cuke4duke and ioke from my .m2/repository and running mvn integration-test passes

**Comment by aslakhellesoy** [comment]
Fixed in 0.8-SNAPSHOT
