### ISSUE TITLE
Guice fails when trying to instantiate anonymous and non-static inner classes in step classes

### ISSUE THREAD

**Issue by nightscape** [cucumber-attic/cuke4duke#33]
When a step class contains anonymous or inner classes, these classes get compiled to their proper .class files, e.g. BackendSteps$1.class
The Guice factory tries to instantiate those classes which is not possible.
I fixed this by wrapping the instantiation code in a try ... catch block, so that the Guice factory continues instead of cancelling.
The code is in my repository at http://github.com/nightscape/cuke4duke

Best regards
  Martin

**Comment by aslakhellesoy** [comment]
I would like to see a test or feature that fails without your fix before adding this.

Also, please respect the coding conventions already in the code - 4 spaces indentation.

And finally, if you fix several unrelated things on your fork, please make a branch for each - that makes it easier for me to merge stuff in. (Your maven stuff doesn't look ready yet).

**Comment by aslakhellesoy** [comment]
Any progress on adding tests?

**Comment by nightscape** [comment]
I've been on vacation the last days, need to catch up at work a little, than I will look into writing the corresponding tests.
I'll post a reply here on the issue when I'm done.

**Comment by nightscape** [comment]
I've implemented a testcase, which shows the problem not on a file level (.class files of anonymous and inner classes being picked up) but by directly using addClass on GuiceFactory.
Unfortunately, I'm not experienced enough in Git to remove the Maven stuff from the branch of the fix, but the fix only concerns GuiceFactory, GuiceFactoryTest and SomeModule.
If you can give me a hint about how I can split off the Maven stuff I will do that as well.

**Comment by aslakhellesoy** [comment]
Thanks for that. Don't worry about separating the stuff now. I can cherry-pick the commits I want. Here is a rough guide you can follow if you should want to contribute more: http://wiki.github.com/dchelimsky/rspec/topic-branches

(instead of git format-patch master, just do a git push origin my_topic)

**Comment by nightscape** [comment]
Thanks for developing such a great testing tool!
I think I got that with git, next time it'll be a clean fast-forward :)
Should I close the ticket or do you close it once you've reviewed the changes?

**Comment by aslakhellesoy** [comment]
Thanks mate. I'll close the ticket when I have merged in your commits and pushed them to my repo. Hope to get to it within a week, hopefully less. Definitely before next release.

**Comment by aslakhellesoy** [comment]
Cleaned up indentation and code. Closed by 8158505b2313ca0f9bc9b4383c4421e316932e78

**Comment by aslakhellesoy** [comment]
With respect to indentation - please use the conventions already present in the code - 4 space indentation.

**Comment by nightscape** [comment]
Oops, sorry...
Just writing some Scala stuff, for which indentation is 2 spaces. Forgot to set it back in Eclipse before formatting...
