### ISSUE TITLE
Groovy Example Fails

### ISSUE THREAD

**Issue by RobertFischer** [cucumber-attic/cuke4duke#34]
Just a straight "ant" fails with the following message:

Smokejumper-MBP:groovy robert$ ant
Buildfile: build.xml

compile-main:
    [mkdir] Created dir: /Users/robert/dev/workspace/cuke4duke/examples/groovy/target/classes
    [javac] Compiling 1 source file to /Users/robert/dev/workspace/cuke4duke/examples/groovy/target/classes

cucumber:
    [mkdir] Created dir: /Users/robert/dev/workspace/cuke4duke/examples/groovy/target/junit-report
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: org/jruby/Main

BUILD FAILED
/Users/robert/dev/workspace/cuke4duke/examples/groovy/build.xml:22: Java returned: 1

Total time: 2 seconds

Didn't see any dependencies resolved, so I ran "ant install-deps".  Got lots of noise, which ended with this:

[ivy:retrieve] .. (0kB)
[ivy:retrieve]  [SUCCESSFUL ] com.thoughtworks.xstream#xstream;1.3.1!xstream.jar (1225ms)
[ivy:retrieve] :: resolution report :: resolve 3694ms :: artifacts dl 31719ms
[ivy:retrieve]  :: evicted modules:
[ivy:retrieve]  junit#junit;3.8.2 by [junit#junit;4.7] in [default]
[ivy:retrieve]  junit#junit;3.8.1 by [junit#junit;4.7] in [default]
    ---------------------------------------------------------------------
    |                  |            modules            ||   artifacts   |
    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    ---------------------------------------------------------------------
    |      default     |   19  |   5   |   0   |   2   ||   20  |   9   |
    ---------------------------------------------------------------------
[ivy:retrieve] 
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]      module not found: cuke4duke#cuke4duke;0.1.8-SNAPSHOT
[ivy:retrieve]  ==== cukes: tried
[ivy:retrieve]    -- artifact cuke4duke#cuke4duke;0.1.8-SNAPSHOT!cuke4duke.jar:
[ivy:retrieve]    http://cukes.info/maven/cuke4duke/cuke4duke/0.1.8-SNAPSHOT/cuke4duke-0.1.8-SNAPSHOT.jar
[ivy:retrieve]  ==== codehaus: tried
[ivy:retrieve]    -- artifact cuke4duke#cuke4duke;0.1.8-SNAPSHOT!cuke4duke.jar:
[ivy:retrieve]    http://repository.codehaus.org/cuke4duke/cuke4duke/0.1.8-SNAPSHOT/cuke4duke-0.1.8-SNAPSHOT.jar
[ivy:retrieve]  ==== ibiblio: tried
[ivy:retrieve]    -- artifact cuke4duke#cuke4duke;0.1.8-SNAPSHOT!cuke4duke.jar:
[ivy:retrieve]    http://repo1.maven.org/maven2/cuke4duke/cuke4duke/0.1.8-SNAPSHOT/cuke4duke-0.1.8-SNAPSHOT.jar
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      :: cuke4duke#cuke4duke;0.1.8-SNAPSHOT: not found
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] :::: ERRORS
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve]  unknown resolver default-mvn-repo
[ivy:retrieve] 
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

**Comment by aslakhellesoy** [comment]
This was very hard to read. Can you paste this into a gist and linkt to it from this ticket?

**Comment by aslakhellesoy** [comment]
I haven't found a way to tell Ivy to download Maven SNAPSHOT dependencies. This will work if you check out a release tag of cuke4duke - which don't use any SNAPSHOT dependencies. -Otherwise you have to use Maven I'm afraid.
