### ISSUE TITLE
cucumber_java muliple subclasses from a parent that has a @Before("") failing in spring / pico container

### ISSUE THREAD

**Issue by ssmithstone** [cucumber-attic/cuke4duke#35]
In my step definitions I need a WebClient for html unit , so I wondering what the best way to do this is, 

I'm running the features inside of a spring container and I have a super abstract class that has a @Before with a method

code at http://pastie.org/669991

then i get the following error message

http://pastie.org/669993

Am i doing something wrong in my design or is there something I am missing

**Comment by aslakhellesoy** [comment]
This is a bug tracker, not a discussion forum. Please use the Cucumber mailing list for general questions.
