### ISSUE TITLE
Pass proxy settings to gem for bootstrapping

### ISSUE THREAD

**Issue by ordnungswidrig** [cucumber-attic/cuke4duke#36]
Maven proxy setting are not passed to gem when bootstrapping using 

mvn -Dcucumber.installGems=true cuke4duke:cucumber

I tried to set the environment variable http_proxy but this has no effect, at least on windows.

**Comment by aslakhellesoy** [comment]
I don't have a proxy handy. Any suggestions how I can test this?

**Comment by ordnungswidrig** [comment]
First FYI, I got the gem installed by manually calling gem install with --http-proxy. I just ran maven -X and copy-pasted the call to jruby/gem that maven-cucumber-plugin uses.

How to test this? This depends on your system. Basically I'd block outgoing connections on port 80 and have sth. like "netcat" listening on any other port, say 44444 (nc -l -p 44444). If you set the proxy for maven to localhost:4444 you should see a connection attempt on made by it. You'd better run maven -o to be sure the request comes from cucumber and not from maven itself.

**Comment by aslakhellesoy** [comment]
So this should work then:

<pre>
&lt;gem&gt;cucumber --http-proxy http://your.proxy:8080&lt;/gem&gt;
</pre>


Can you confirm?

**Comment by ordnungswidrig** [comment]
Yes, that should do the job.

**Comment by aslakhellesoy** [comment]
Ok, so nothing to do then - except for updaating the wiki.

**Comment by aslakhellesoy** [comment]
Here it is: http://wiki.github.com/aslakhellesoy/cuke4duke/installing-gems

**Comment by ordnungswidrig** [comment]
The problem is that you'll have to maintain the proxy settings at two places: general maven settings and for gem. Is there a way to expose the maven proxy settings as a property? I googled but I did not find an answer.

**Comment by aslakhellesoy** [comment]
That's a minor problem IMO. But if you provide a fix for this I'll merge it in of course. The Mojo could just add the flag transparently if the maven proxy is set. I'd like to reopen this ticket, but that's not possible. Just comment here if you provide a fix - I still get notifications.

**Comment by nealeu** [comment]
This looks like one that I can pick up.  We could really do with proxy from settings.xml being used, as otherwise it creates hell for our client.

How does this sound:
If the c4d plugin sees a <gem>install line without --http-proxy, and there is an active maven proxy in the reactor, then add the -http-proxy entry as appropriate.

Naturally, I'll assume, for the moment that no authentication is required, and perhaps emit a warning if auth credentials are found.

**Comment by nealeu** [comment]
Done a bit of hunting around.  Here's an example of how to get at settings for http proxy:
Add Settings for injection by maven.
    /**
    \* @parameter expression="${settings}"
    \* @required
    \* @readonly
    */
    private Settings settings;

And then this looks like what we'll need to access them:

```
Proxy activeProxy = this.settings.getActiveProxy();
.. activeProxy.getHost(); 
.. activeProxy.getPort(); // etc
```

**Comment by nealeu** [comment]
This is now fixed in my fork: nealeoc/cuke4duke
