### ISSUE TITLE
@Before("@scenario") does not work as expected

### ISSUE THREAD

**Issue by olemartin** [cucumber-attic/cuke4duke#38]
I thought that an @Before("scenario") should only be ran before scenarios that had the @scenario annotation. However, it seems like the @Before method is ran before all scenarios.

**Comment by aslakhellesoy** [comment]
You're right. I have reproduced it on trunk. What Cuke4duke and Cucumber versions are you using?

BTW, @Before("@mytag") is the way to use it, @Before("mytag") - without the @ should ideally not be run ever. Once this bug is fixed that is.

**Comment by olemartin** [comment]
I followed the example here: http://github.com/aslakhellesoy/cuke4duke/tree/master/examples/java-webdriver/
I am using cuke4duke 0.1.8 and cucumber 0.4.3

**Comment by aslakhellesoy** [comment]
Let the ruby side handle tag filtering. We weren't doing any tag filtering at all. Closed by 76f6df114e50cac1c6e573c5a8605a446e4e4b73.

**Comment by aslakhellesoy** [comment]
Beware that you need trunk of cucumber to use this. I had to make a little change there too. So build everything yourself or wait for a new release of both.
