### ISSUE TITLE
How do you control the order of @Before methods

### ISSUE THREAD

**Issue by olemartin** [cucumber-attic/cuke4duke#39]
I have two methods with the @Before annotation, and I want the order to matter. How do I control the order of the invocations?

**Comment by aslakhellesoy** [comment]
I would expect the execution order to be the order of instantiation of the classes they live in. I would also expect the order of execution of several Before hooks within the same class to be the order of declaration in that class.

I haven't verified if this is the case. It just might be working that way by chance. If not we have an interesting problem to solve. I hope we don't have to come up with numbered arguments.

BTW, After hooks should always run in the opposite order of Before hooks.

**Comment by olemartin** [comment]
The order seems kind of random right now. I have two @Before hooks declared in the same class, and the last method is ran before the first one.
I am testing cuke4duke with webdriver and I have one hook that bring up the browser, and another one that login the user. The order of these are obviously important :)

You may add an optional order-argument to the annotation that is used if the order is important for the end-user.

**Comment by aslakhellesoy** [comment]
Is it so that you only want to log in in certain scenario? If not, a workaround until this is fixed could be to do it all in one @Before block.

We could add an order number, but it would be nicer if cuke4duke followed the rules I outlined above, don't you think?

**Comment by aslakhellesoy** [comment]
I ended up adding a new @Order annotation: http://wiki.github.com/aslakhellesoy/cuke4duke/hooks
