### ISSUE TITLE
java -jar cuke4duke.jar features

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#40]
I want a way to run cuke4duke just like cucumber. It should also pick up jar files automatically. Example: --require lib

Some thoughts here too:
http://groups.google.com/group/cukes/browse_thread/thread/961ca23e20db2830

**Comment by aslakhellesoy** [comment]
What I mean is:

java -jar cuke4duke.jar (same args as cucumber)

**Comment by aslakhellesoy** [comment]
And the jar should also ship with the basic gems inside the jar. ref convo with gaffo_home: http://irclogger.com/cucumber/2009-11-19

**Comment by gaffo** [comment]
+1

**Comment by aslakhellesoy** [comment]
I've been experimenting a little with this. I'll probably end up packaging cuke4duke as a gem that can be installed with a regular jruby installation. Then do: cuke4duke [regular cucumber arguments]

**Comment by aslakhellesoy** [comment]
Fixed in 0.2.1
