### ISSUE TITLE
Update gems from Ant

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#43]
http://blog.confabulus.com/2009/12/08/updating-embedded-jruby-gems-with-ant/

Make it all an antlib and distribute with the cucumber core jar.

**Comment by gaffo** [comment]
that's fine. Just link me in the changelog or somthing so my bright ideas populate faster :)
this should almost be an extension to jruby don't you think? And the mojo class as well.

**Comment by aslakhellesoy** [comment]
This can now be done via the <gem> task.
