### ISSUE TITLE
Relax exact version dependency on cucumber in cuke4duke.rb

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#44]
Should use >=

**Comment by gaffo** [comment]
also seems to be an exact requirement on treetop and I can't find that anywhere.

**Comment by aslakhellesoy** [comment]
The exact dep on Treetop would be in the Cucumber's Rakefile. Feel free to relax that too.

**Comment by aslakhellesoy** [comment]
This is fixed on master
