### ISSUE TITLE
Cucumber in Java doesn't actually exit correctly if daemon threads are running

### ISSUE THREAD

**Issue by gaffo** [cucumber-attic/cuke4duke#45]
The use of Kernel.exit in the cucumber executable script line 10 only seems to exit the jruby thread. In normal ruby this works because it stops the ruby vm. However in java, if there are server threads hanging around (say we started up jetty), then the cuke run will never end. 

The ugly solution is to change the Kernel.exit to be java.lang.System.exit(failure ? 1 : 0)
Of course this doesn't work on normal ruby. I'd suggest that we defer to a library to shut down the system. And any individual language can implement it's hook as it sees fit.

For java this would be to override it with java.lang.System.exit which shuts down the whole JVM instead of just the ruby vm inside of the jvm. 

If you agree to this approach, I will submit a patch.

**Comment by aslakhellesoy** [comment]
So something like this?

<pre>
if defined?(JRUBY_VERSION) ? java.lang.System.exit(failure ? 1 : 0) : Kernel.exit(failure ? 1 : 0)
</pre>


Should work fine. It's a Cucumber patch though.

**Comment by aslakhellesoy** [comment]
I have tried to reproduce a simple scenario where I create a Java daemon thread with an inifinite loop, and exit with Kernel.exit(1):

http://gist.github.com/256870

It exits nicely for me, and kills the Java daemon thread.

Can you please provide me with a simple example that illustrates how daemon threads are left hanging around? (A modification of my gist would be better than a big example using jetty).

**Comment by gaffo** [comment]
Okay, after reading http://journals.ecs.soton.ac.uk/java/tutorial/java/threads/daemon.html it's not a daemon thread. Jetty would be a daemon in unix land but not in java it seems as jetty wouldn't want you to quit the app while it's running. So I think if you take the isDaemon off of it you'll see my issue.

**Comment by aslakhellesoy** [comment]
No, I don't see your issue when I remove the setDaemon(true) call. Still can't reproduce.

**Comment by gaffo** [comment]
Hrm. It happens for me when I get enough frameworks up (my app is complicated :)) and it just never ends with the kernel one. I'll have to experiment to see what is the likely cause.

**Comment by aslakhellesoy** [comment]
Any news on this? Still not sure how to reproduce.

**Comment by aslakhellesoy** [comment]
cannot reproduce
