### ISSUE TITLE
Document how to use a debugger

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#47]

**Comment by torbjornvatn** [comment]
I've added documentation for maven debugging to the wiki.

**Comment by aslakhellesoy** [comment]
Great! It doesn't look Maven specific at all (except that MAVEN_OPTS is used to send the args to the JVM when using Maven). The docs don't have to be Eclipse-specific either.

So I think the page should just be renamed to "Debugging"

**Comment by torbjornvatn** [comment]
I've tried to rewrite the Debug Cuke4Duke Steps page to be more generic, but I added a Maven section at the bottom though.
Seems like I can't rename or delete pages, maybe you can delete "Debug Cuke4Duke Maven plugin" and rename "Debug Cuke4Duke Steps" to "Debugging"?

**Comment by aslakhellesoy** [comment]
Done!
