### ISSUE TITLE
Multiline String cannot convert to cuke4duke.Table

### ISSUE THREAD

**Issue by SuperWes** [cucumber-attic/cuke4duke#50]
Our feature has a line that reads,

```
Then I should see
    """
    Some Words!
    Some more words.
    A lot of wordy word word word word word word word word word word word word word word word word word word word wordy words
    """
```

Which generates:

```
Then /^I should see this$/ do |string|
    pending # express the regexp above with the code you wish you had
end
@Then("^I should see this$")
@Pending
public void iShouldSeeThisWithString(cuke4duke.Table string) {
}
```

But when I try to run the cuke I'm getting the following error:

```
Sorry, cuke4duke doesn't know how to convert a org.jruby.gen.InterfaceImpl716911626@bf711e (class org.jruby.gen.InterfaceImpl716911626) to type interface cuke4duke.Table (NativeException)
  features/initialization/10048.feature:42:in `Then I should see'
```

Any idea what's going on here?

**Comment by aslakhellesoy** [comment]
I don't understand what this has to do with tables. Use this:

<pre>
@Then("^I should see")
public void iShouldSee(String labelText) {
        if (labelText.contains("\\n"))
        {
        }
}
</pre>


http://wiki.github.com/aslakhellesoy/cucumber/multiline-step-arguments

Please only use the issue tracker for bug reports and feature requests. Use the mailing list for questions.

**Comment by SuperWes** [comment]
Yeah, my second section had a typo. I believe there might be a bug in the @Pending suggestions that are provided by cuke4duke. I'll edit the original post to better represent what my issue was. Regardless, your suggestion helped, so thanks!

**Comment by SuperWes** [comment]
Here's more information. The suggestion was:

```
 @Then("^I should see this$")
 @Pending
 public void iShouldSeeThisWithString(cuke4duke.Table string) {
 }
```

Which I believe is the wrong suggestion. So I guess this is a problem with the suggestions.

**Comment by aslakhellesoy** [comment]
Ok now I understand what you mean. I've created a new ticket: #51
