### ISSUE TITLE
Installing gems from maven seems not to work

### ISSUE THREAD

**Issue by jbandi** [cucumber-attic/cuke4duke#53]
Installing gems from maven fails.
See the following gist:

http://gist.github.com/261285

I think the following command is issued:

jruby -S gem cucumber --version 0.5.1 --source http://gems.rubyforge.org/ 

... which cant work, since the 'install' is missing between gem' and 'cucumber'.

A hack is to include the install in the gem specification in the pom.xml, like this:

```
          <gems>
            <gem>install cucumber --version 0.5.1 --source http://gems.rubyforge.org/</gem>
          </gems>
```

**Comment by aslakhellesoy** [comment]
You're right that install is needed. See the release notes :-)
http://github.com/aslakhellesoy/cuke4duke/blob/v0.2.0/History.txt

**Comment by jbandi** [comment]
Sorry...
