### ISSUE TITLE
Groovy example fails - undefined method `tag_expressions' 

### ISSUE THREAD

**Issue by clemens68** [cucumber-attic/cuke4duke#56]
Since yesterday I get
... 
[cucumber] undefined method `tag_expressions' for #Java::Cuke4dukeInternalGroovy::GroovyHook:0x29483 (NoMethodError)
...
when running the Groovy example. This used to work...

**Comment by clemens68** [comment]
I am running the example through ant
ant -Divy=true -Dgems=true

**Comment by aslakhellesoy** [comment]
Dupe of #56

**Comment by clemens68** [comment]
Dupe of #57 ?

**Comment by aslakhellesoy** [comment]
Yes, I think this is a duplicate of issue #57 because you seem to be running against a cucumber codebase that isn't uptodate with my master. If you're using cuke4duke master you also need cucumber master.
