### ISSUE TITLE
Cuke4Duke should ignore abstract classes when resolving steps

### ISSUE THREAD

**Issue by dashorst** [cucumber-attic/cuke4duke#58]
I'm trying to build a cuke4duke/[Apache Wicket](http://wicket.apache.org) integration, and I want to make it easy for people to configure their steps.

In this case: I want to create an abstract class `WicketSteps` that provides the `iShouldSee`, `iClickTheLinkWithText` and `iAmViewing` methods. Users would then extend the `WicketSteps` and provide it with the necessary configuration such that Wicket knows which application to test.

cuke4duke now refuses to run the features and throws an ambiguity error since it discovers the steps defined in the abstract class _and_ in the concrete step classes for each feature (which inherit them from the `WicketSteps` class).

**Comment by aslakhellesoy** [comment]
On what subclass instance did you expect the method to be invoked? Can you share some code?

**Comment by aslakhellesoy** [comment]
I need to see both code and error messages (and software versions) to be able to answer your questions.

**Comment by dashorst** [comment]
Try this project: 
dashorst/cucumber-wicket@c070ccb16755c30df35b2bc99c3f34f291a9675a

**Comment by aslakhellesoy** [comment]
Allow me to explain how Cuke4Duke works. 

1) Before any execution starts, Cuke4Duke scans your --require'd classes for @Given, @When and @Then annotations. For each concrete class that has a method (including inherited ones) with one of these annotations a StepDefinition object is created (which holds a reference to the regexp and the java.lang.reflect.Method object).

2) Before a scenario starts executing, Cuke4Duke will instantiate an object for each class with annotations. (Cuke4Duke uses PicoContainer, Spring or Guice for this). In your case it will instantiate a CountingSteps and HelloWorldSteps instance. There is never any coupling (implicit or explicit) between a feature file and a step definition class. A feature won't "pick" step definitions from any particular class - it's only based on Regexp matching.

3) Before a step is executed Cuke4Duke will look for StepDefinition objects with a matching Regexp. If it finds one, it will invoke the method on the instance that was created in step 2. In your case, Cuke4Duke has no way of knowing whether to invoke the method on the CountingSteps instance or the HelloWorldSteps instance, and bails. (I'll improve the error message in the next release to make it easier to understand).

This means that using inheritance for StepDefinitions is something you should avoid. It will inevitably lead to ambiguous errors if you have 2 or more concrete subclasses.

There are several alternative approaches you can use instead. I have made some modifications that use tags: http://github.com/aslakhellesoy/cucumber-wicket/commit/9207424b4256d9181183c8575f677502c3272fe6

Another option could be to not use tags, but instantiate the tester object in the first step. Example:

<pre>
Given I am viewing the hello world home page # => tester = new WicketTester(new HelloWorldApplication());
Given I am viewing the hello counting home page # => tester = new WicketTester(new CountingApplication());
</pre>


Hope this helps.

Is this for a revised edition of your Wicket in Action book?

**Comment by dashorst** [comment]
Updated my project to use your suggestion: http://github.com/dashorst/cucumber-wicket/tree/d561229d5a70ce15c71275815ba4b749fac2e67d

This is not for a new edition of Wicket in Action (none is in the works AFIAK). I'm just very interested in making testing much easier, and cucumber is currently one of the things I'd like to introduce in my company and the Wicket community.

**Comment by aslakhellesoy** [comment]
Global hooks:

<pre>
@Before
public void runsBeforeEachScenario() {}
</pre>


Tagged hooks:

<pre>
@Before("@foo,@bar")
public void runsBeforeEachScenarioTaggedWithFooOrBar() {}
</pre>


More info here: http://wiki.github.com/aslakhellesoy/cucumber/hooks

**Comment by aslakhellesoy** [comment]
Decided not to fix this, so closing it.
