### ISSUE TITLE
Groovy Example not Running

### ISSUE THREAD

**Issue by MachinesAreUs** [cucumber-attic/cuke4duke#66]
When trying cuke4duke in my own project I´ve got
[INFO] [cuke4duke:cucumber {execution: default-cli}]
[INFO] No such file or directory - No such file or directory - /Users/agus/certum/integracion/plaÌticas teÌcnicas/chess/chess-swing-gui/features (Errno::ENOENT)
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:118:in `feature_dirs'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:118:in`each'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:118:in `map'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:118:in`feature_dirs'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:182:in `require_dirs'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:76:in`all_files_to_load'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/configuration.rb:94:in `support_to_load'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/main.rb:48:in`execute!'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/main.rb:20:in `execute'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/bin/cucumber:8
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/bin/cucumber:13:in`load'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cuke4duke-0.2.4-java/bin/cuke4duke:13
[INFO] /Users/agus/.m2/repository/.jruby/gems/cuke4duke-0.2.4-java/bin/cuke4duke:19:in `load'
[INFO] /Users/agus/.m2/repository/.jruby/bin/cuke4duke:19
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] JRuby failed.

Embedded error: Java returned: 1

Then I decided to try the groovy example in the repository, but I get a similar problem,
could it be a versions related problem?

[INFO]   Scenario: Regular numbers                    # features/division.feature:7
[INFO] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
[INFO] /Users/agus/Development/workz/cucumber/cuke4duke/examples/groovy/features/step_definitions/CalculatorSteps.groovy: 15: unable to resolve class calc.Calculator 
[INFO]  @ line 15, column 10.
[INFO]      calc = new calc.Calculator()
[INFO]             ^
[INFO] 
[INFO] 1 error
[INFO](NativeException)
[INFO] org/codehaus/groovy/control/ErrorCollector.java:296:in `failIfErrors'
[INFO] org/codehaus/groovy/control/CompilationUnit.java:860:in`applyToSourceUnits'
[INFO] org/codehaus/groovy/control/CompilationUnit.java:521:in `doPhaseOperation'
[INFO] org/codehaus/groovy/control/CompilationUnit.java:497:in`processPhaseOperations'
[INFO] org/codehaus/groovy/control/CompilationUnit.java:474:in `compile'
[INFO] groovy/lang/GroovyClassLoader.java:292:in`parseClass'
[INFO] groovy/lang/GroovyShell.java:727:in `parseClass'
[INFO] groovy/lang/GroovyShell.java:739:in`parse'
[INFO] groovy/lang/GroovyShell.java:574:in `evaluate'
[INFO] groovy/lang/GroovyShell.java:623:in`evaluate'
[INFO] cuke4duke/internal/groovy/GroovyLanguage.java:39:in `begin_scenario'
[INFO] (__FORWARDABLE__):3:in`begin_scenario'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/language_support/language_methods.rb:12:in `before'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/step_mother.rb:325:in`before'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/step_mother.rb:324:in `each'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/step_mother.rb:324:in`before'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/step_mother.rb:306:in `before_and_after'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/scenario.rb:45:in`accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/scenario.rb:100:in `with_visitor'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/scenario.rb:39:in`accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:51:in `visit_feature_element'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:50:in `visit_feature_element'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/feature.rb:26:in`accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/feature.rb:25:in `each'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/feature.rb:25:in`accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:20:in `visit_feature'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:19:in `visit_feature'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/features.rb:29:in`accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/features.rb:17:in `each'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/features.rb:17:in`each'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/features.rb:28:in `accept'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:14:in`visit_features'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:180:in `broadcast'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/ast/tree_walker.rb:13:in`visit_features'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/main.rb:61:in `execute!'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/lib/cucumber/cli/main.rb:20:in`execute'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/bin/cucumber:8
[INFO] /Users/agus/.m2/repository/.jruby/gems/cucumber-0.6.4/bin/cucumber:13:in `load'
[INFO] /Users/agus/.m2/repository/.jruby/gems/cuke4duke-0.2.4-java/bin/cuke4duke:13
[INFO] /Users/agus/.m2/repository/.jruby/gems/cuke4duke-0.2.4-java/bin/cuke4duke:19:in`load'
[INFO] /Users/agus/.m2/repository/.jruby/bin/cuke4duke:19
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] JRuby failed.

Embedded error: Java returned: 1

**Comment by aslakhellesoy** [comment]
When you copy build scripts from the examples, make sure you check out a tag instead of taking them from the master branch. (The master branch requires that you build all dependent libraries from master too - see http://wiki.github.com/aslakhellesoy/cuke4duke/build-cuke4duke for how to do that.
