### ISSUE TITLE
How do I get a full stack trace for Java exceptions

### ISSUE THREAD

**Issue by mat** [cucumber-attic/cuke4duke#67]
When running a Java step definition cuke4duke does not display a stack trace when an exception is thrown. Instead you get a NativeException which only displays the type of the Java exception. Is there a command line parameter to enable display of full stack trace or something I'm not aware of?

```
Given foo
  | name   | value  |
  | adidas | adidas |
  | puma   | puma   |
  java.lang.NullPointerException: null (NativeException)
  features\foobar.feature:8:in `Given foo'
And bar
```

**Comment by mat** [comment]
The problem seemed to be that the NPE occured because Guice couldn't create the steps class. If there is an easy way for you to detect that a step class could not be instantiated and give a better error message this would be nice.
Otherwise just close this bug.
  Thanks!

**Comment by aslakhellesoy** [comment]
--backtrace. Please use the cucumber mailing list for questions (link on cukes.info).

This is a bug tracker.
