### ISSUE TITLE
Expose Spring beans to Groovy-based step definitions

### ISSUE THREAD

**Issue by cebartling** [cucumber-attic/cuke4duke#69]
I'm using a mix of Java and Groovy step definitions and hooks.  For the Java hooks, I'm using the @StepDefinition annotation and using the SpringFactory.  It's unclear to me how to get Groovy involved so that Groovy step definitions have access to the Spring application context.

**Comment by judoole** [comment]
Did you ever find a way around this?

**Comment by cebartling** [comment]
I am not using cuke4duke anymore.  Moved on to other solutions.
