### ISSUE TITLE
Compare tables with mixed rows

### ISSUE THREAD

**Issue by dz-eta** [cucumber-attic/cuke4duke#75]
Hello. 

The Java class cuke4duke.Table  contains a few methods (diffLists, diffHashes) to compare tables.

Is it possible to add another comparator, which will not be affected by the row order?

For example, comparator will accept these tables as equal

Table 1: (Entry, Count) : [ (Notebook, 5); (Mouse, 15); (Keyboard, 10) ]
Table 2: (Entry, Count) : [ (Keyboard, 10); (Notebook, 5); (Mouse, 15) ]

This may be useful in asynchronous applications, where order of message-flow is not determined.

**Comment by aslakhellesoy** [comment]
The implementation of the diffing algorithm is in cucumber (ruby). While it's certainly possible, it has very low priority right now. In any case, please request this in Cucumber's own bug tracker. I recommend you sort the data before doing the diff.
