### ISSUE TITLE
Dependency conflict with cuke4duke 0.3.2, gherkin-2.1.4 and cucumber-0.9.0 ruby gem

### ISSUE THREAD

**Issue by mjul** [cucumber-attic/cuke4duke#77]
Cuke4duke 0.3.2 declares a dependency to gherkin 2.1.4 in the pom.xml.
However, it uses the cucumber-0.9.0 ruby gem which requires gherkin 2.2.4.

Hence, I get the following error when running it

cucumber-tutorial mjul$ lein cuke
wrong # of arguments(2 for 1) (ArgumentError)
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/feature_file.rb:35:in `feature'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/feature_file.rb:35:in`parse'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime/features_loader.rb:28:in `load'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime/features_loader.rb:26:in`each'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime/features_loader.rb:26:in `load'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime/features_loader.rb:14:in`features'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime.rb:179:in `features'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/runtime.rb:32:in`run!'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/cli/main.rb:54:in `execute!'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/../lib/cucumber/cli/main.rb:29:in`execute'
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/cucumber:8
/Users/mjul/src/github/mjul/cucumber-tutorial/lib/gems/gems/cucumber-0.9.0/bin/cucumber:19:in `load'
lib/gems/bin/cucumber:19

The dependencies downloaded are these (on the Java side):

cucumber-tutorial mjul$ ls lib/dev/
ant-1.6.5.jar                       maven-ant-tasks-2.0.10.jar
ant-1.8.1.jar                       maven-artifact-2.0.10.jar
ant-launcher-1.8.1.jar                  maven-artifact-manager-2.0.10.jar
clansi-1.0.0.jar                        maven-error-diagnostics-2.0.10.jar
classworlds-1.1-alpha-2.jar                 maven-model-2.0.10.jar
clj-stacktrace-0.1.2.jar                    maven-plugin-registry-2.0.10.jar
clojure-1.2.0-beta1.jar                 maven-profile-2.0.10.jar
clojure-contrib-1.2.0-RC3.jar               maven-project-2.0.10.jar
cuke4duke-0.3.2.jar                     maven-repository-metadata-2.0.10.jar
difform-1.1.0.jar                       maven-settings-2.0.10.jar
gherkin-2.1.4.jar                       plexus-container-default-1.0-alpha-9-stable-1.jar
google-diff-match-patch-0.1.jar             plexus-interpolation-1.1.jar
hooke-1.0.2.jar                     plexus-utils-1.5.5.jar
jline-0.9.94.jar                        swank-clojure-1.3.0-20100821.141701-11.jar
jruby-complete-1.5.1.jar                    wagon-file-1.0-beta-2.jar
jtidy-4aug2000r7-dev.jar                    wagon-http-lightweight-1.0-beta-2.jar
junit-3.8.1.jar                     wagon-http-shared-1.0-beta-2.jar
lein-cuke-0.3.2.jar                     wagon-provider-api-1.0-beta-2.jar
lein-difftest-1.3.1.jar                 xml-apis-1.0.b2.jar
leiningen-1.3.1.jar

See the README.md in this cucumber tutorial for a pretty-printed explanation of the problem:
http://github.com/mjul/cucumber-tutorial

The fix is to reference the gherkin 2.2.4 instead.

**Comment by aslakhellesoy** [comment]
Hmm. cuke4duke-0.3.2 has a dep on cucumber-0.8.5 (or any version with a higher _patch_ number). That's what ~> means.

https://rubygems.org/gems/cuke4duke

So this is puzzling. I'm not sure how you got the newer 0.9.0 version.

That said - does cuke4duke seem to work ok with gherkin-2.2.4 + cucumber-0.9.0? I should get a new cuke4duke release out soon...

**Comment by mjul** [comment]
Once I resolved the dependency issue there was no problem: cuke4duke 0.3.2 works fine with gherkin 2.2.4 and cucumber 0.9.0 

Keep up the good work, 
Martin

**Comment by aslakhellesoy** [comment]
Don't declare dependency on gherkin. Closed by d2f7db6917ed3095910d77cbe27a27060575a028.
