### ISSUE TITLE
error for mvn -Dcucumber.installGems=true cuke4duke:cucumber

### ISSUE THREAD

**Issue by adancu** [cucumber-attic/cuke4duke#79]
Hi,

I get this error when running mvn -Dcucumber.installGems=true cuke4duke:cucumber .
I'm not sure which pom.xml cuke4duke expects to find in ".m2/repository/.jruby/gems/cuke4duke-0.4.1"

<pre>
mvn -Dcucumber.installGems=true cuke4duke:cucumber
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building cucumber
[INFO]    task-segment: [cuke4duke:cucumber]
[INFO] ------------------------------------------------------------------------
[INFO] [cuke4duke:cucumber {execution: default-cli}]
[INFO] JRuby limited openssl loaded. http://jruby.org/openssl
[INFO] gem install jruby-openssl for full support.
[INFO] Successfully installed cuke4duke-0.4.1
[INFO] 1 gem installed
[INFO] /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke/version.rb:4:in `initialize': No such file or directory - /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke/../../pom.xml (Errno::ENOENT)
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke/version.rb:4
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke/version.rb:31:in `require'
[INFO]  from file:/home/adancu/.m2/repository/org/jruby/jruby-complete/1.5.3/jruby-complete-1.5.3.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke.rb:3
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/../lib/cuke4duke.rb:31:in `require'
[INFO]  from file:/home/adancu/.m2/repository/org/jruby/jruby-complete/1.5.3/jruby-complete-1.5.3.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/cuke4duke:3
[INFO]  from /home/adancu/.m2/repository/.jruby/gems/cuke4duke-0.4.1/bin/cuke4duke:19:in `load'
[INFO]  from /home/adancu/.m2/repository/.jruby/bin/cuke4duke:19
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] JRuby failed.

Embedded error: Java returned: 1
</pre>

**Comment by aslakhellesoy** [comment]
Dang! I've been reworking the build and packaging and must have screwed up somewhere. I'll look into it...

**Comment by aslakhellesoy** [comment]
Relevant threads:

http://groups.google.com/group/cukes/browse_thread/thread/7b62ab5349a99c6a
http://groups.google.com/group/cukes/browse_thread/thread/ec7b22363fadd642

**Comment by aslakhellesoy** [comment]
Bugfix: error for mvn -Dcucumber.installGems=true cuke4duke:cucumber. Closed by 1b36b51952d8db2fd33d3651e7233896001c6510.
