### ISSUE TITLE
Using external jar in Java step definitions (lauching cuke4duke through maven)

### ISSUE THREAD

**Issue by mBread** [cucumber-attic/cuke4duke#82]
I'm using cuke4duke in maven, and am trying to include an external Java library to use in my Java step definitions. The --require parameter doesn't seem to be working, and trying to use the -cp argument in the jvm args element of the Maven POM file is rejected as not recognised. Any ideas what I can do?

When trying to use the --require parameter:
          <cucumberArgs>
            <cucumberArg>${basedir}/src/test/java</cucumberArg>
            <cucumberArg>--require ${basedir}/lib/abbot.jar</cucumberArg>
            <cucumberArg>--require target/test-classes</cucumberArg>
          </cucumberArgs>
I get a ClassNotFoundException:
    [INFO] --- cuke4duke-maven-plugin:0.4.2:cucumber (run-features) @ quelea-cucumber ---
    [INFO] java.lang.NoClassDefFoundError: junit/extensions/abbot/ComponentTestFixture (NativeException)

Trying to add it in as a jvmArg:
          <jvmArgs>
            <jvmArg>
              -Dcuke4duke.objectFactory=cuke4duke.internal.jvmclass.PicoFactory
            </jvmArg>
            <jvmArg>
              -cp ${basedir}/lib/abbot.jar
            </jvmArg>
          </jvmArgs>
isn't recognised:
    [INFO] --- cuke4duke-maven-plugin:0.4.2:cucumber (run-features) @ quelea-cucumber ---
    [INFO] Unrecognized option: -cp /Users/mbread/Desktop/quelea-cucumber/lib/abbot.jar
    [INFO] Could not create the Java virtual machine.

How do I load this jar so it can be used from my step definitions?

Thanks

**Comment by aslakhellesoy** [comment]
Just use a regular pom <dependency>

**Comment by mBread** [comment]
Thanks, got it sorted now. Can close the issue now.

For future reference, if anyone else needs it, I used the systemPath element & the 'system' scope, as described here: http://maven.apache.org/ref/3.0/maven-model/maven.html#class_dependency
