### ISSUE TITLE
maven plugin doesn't add test scoped dependencies

### ISSUE THREAD

**Issue by darrinholst** [cucumber-attic/cuke4duke#9]
When the maven plugin is building the classpath it tries to add the entries required for the test scope with the ${project.testClasspathElements} variable but that only works if you set @requiresDependencyResolution test. With this fixed you can now set the cucumber dependencies to test in the pom so they are not included in the final package.

fix is at http://github.com/darrinholst/cuke4duke/commit/f25b9a5b4dd76adb3ea999149b3ec693bf1b2dba

**Comment by aslakhellesoy** [comment]
This was fixed in 0.1.2
