### ISSUE TITLE
http://cukes.info/maven is down

### ISSUE THREAD

**Issue by ayratn** [cucumber-attic/cuke4duke#93]
http://cukes.info/maven is used as maven repository everywhere in examples but doesn't work at the moment

**Comment by aslakhellesoy** [comment]
I had to switch host and haven't gotten around to bring the old repo back yet. Thanks for letting me know.

**Comment by ziobrando** [comment]
Hanging on this one also.
But ... no hurry, it's Christmas :-)

**Comment by jrh3k5** [comment]
+1 to this. We're looking into using Cucumber with our Java EE application and the lack of a Maven repo is an inconvenience now and definitely a blocker when we go to officially deploy (as we use Electric Commander on a box controlled by someone else).

**Comment by jkodumal** [comment]
Another +1 from me =)

**Comment by jarltotland** [comment]
Really hope you can put this back up somewhere soon, building everything up to and including  cucumber-maven-plugin is complicated and takes a lot of time for us ruby-newbies.

**Comment by mayanksahai** [comment]
setting up an environment to test a java app but unable to progress. can you pleae put it back soon ?

**Comment by leifbladt** [comment]
+1 from me

**Comment by eivinhb** [comment]
I'll join in. :) +1

**Comment by aslakhellesoy** [comment]
Sorry about this folks. I'll do my best to resurrect today or tomorrow.

**Comment by oc** [comment]
What about just deploying to: http://nexus.sonatype.org/oss-repository-hosting.html?

**Comment by aslakhellesoy** [comment]
Hi. The repository is up again. Sort of. There is currently only one version of cuke4duke there, which I released last night: 0.3.4.

I wasn't able to salvage older binaries. (I've had several problems with my previous hosting company and domain registrar, which should all be solved now).

I hope you are all able to just point to the new version and carry on like before. The repository isn't browsable, I'll work on that. Maven should be able to download artifacts though,

@oc - I'll consider deploying to sonatype in the future. I wasn't aware of that option.

Please give me a heads up on how this works for you so I can close this ticket.

**Comment by ziobrando** [comment]
Hi Aslak, gave it a try but didn't work.

is the repository correct?

[INFO] Unable to find resource 'cuke4duke:cuke4duke-maven-plugin:pom:0.3.4' in repository cukes (http://cukes.info/maven)

**Comment by leifbladt** [comment]
I'm confused. The version I was using is 0.4.2, and the newest is now 0.3.4? Beside that, both versions are not available in the repository.

**Comment by oc** [comment]
- http://oc.rynning.no/cuke4duke-0.3.2.tgz 
- http://oc.rynning.no/cuke4duke-0.4.2.tgz (may be my own custom build)
- http://oc.rynning.no/cuke4duke-maven-plugin-0.3.2.tgz
- http://oc.rynning.no/cuke4duke-maven-plugin-0.4.2.tgz (as above)

(tarred from ~/.m2/repository/, i.e. cuke4duke/cuke4duke/0.4.2/<files>)

**Comment by aslakhellesoy** [comment]
Sorry folks, I meant 0.4.3, not 0.3.4. 

http://cukes.info/maven/cuke4duke/cuke4duke/0.4.3/cuke4duke-0.4.3.jar

**Comment by aslakhellesoy** [comment]
cuke4duke 0.4.3 is the only version you'll find in the cukes.info maven repo for now. Building the old tags is possible, but a PITA, so if people are happy with 0.4.3 I'll leave it at that.

**Comment by ziobrando** [comment]
0.4.3 is working for me.  :-)

Thanks

**Comment by aslakhellesoy** [comment]
Working as in both downloading and running fine? If I get one more confirmation I'll close this. Sorry again for the mess.

**Comment by leifbladt** [comment]
For me it's both ok.

**Comment by dhay** [comment]
I'm trying to set up our nexus instance to proxy the cukes.info/maven repository, but it's having trouble connecting.  I suspect it has something to do with not being able to browse the cukes.info/maven repository (e.g. I get a HTTP 403 error if I go to http://cukes.info/maven)

**Comment by aslakhellesoy** [comment]
@dhay: directory browsing is on now. I'm closing this issue.

**Comment by dfalves** [comment]
Aslak,

I am referencing version 0.4.3 in my pom, but I am now getting, "The plugin 'cucumber.mojo:cucumber-maven-plugin' does not exist or no valid version could be found"....can you help me out?

David

**Comment by aslakhellesoy** [comment]
Look in the examples to see how it's used. If that doesn't help, please open a new ticket and include relevant pieces of your pom.
